apiVersion: apps/v1
kind: Deployment
metadata:
  name: gunicorn
  labels: 
    app: gunicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gunicorn
  template:
    metadata:
      labels:
        namespace: template
        app: gunicorn
    spec:
      serviceAccountName: test
      containers:
      - name: gunicorn
        image: amazingplum/gunicorn:latest
        ports:
        - containerPort: 8001
          protocol: TCP
